version: '3.8'
service:
  movies:
    image: aquil294/paymovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

    train:
     image: aquil294/paytrain:latest
     ports:
       - "82:80"
     depoy:
       replicas: 3

    dth:
     image: aquil294/paydth:latest
     ports:
       - "83:80"
     deploy:
       replicas: 3

    reacharge:
      image: aquil294/payreacharge:latest
      ports:
        - "84:80"
      deploy:
        replicas: 3
